[package]
name = "clinews"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
serde = {version = "1.0.192", features = ['derive']}
serde_json = "1.0.108"
ureq = {version = "2",features = ["json","charset"] }
newsapi = {path ="./newsapi"}
dotenv = "0.15.0"
