[package]
name = "newsapi"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.192", features = ['derive']}
serde_json = "1.0.108"
thiserror = "2.0.12"
ureq = {version = "2",features = ["json","charset"] }
